changed notifs., added conect. checks

diff --git a/notflix b/notflix
--- a/notflix
+++ b/notflix
@@ -44,12 +44,17 @@ checkDependencies() {
 
   if [ "$useRofi" = false ]; then 
     isInstalled "dmenu" || die "notflix: could not find rofi/dmenu."
+    echo "notflix: using dmenu instead of rofi."
   fi
 }
 
 checkConnection() {
-  result=$(curl -s -o /dev/null -w "%{http_code}" $baseurl) 
-  [ "$result" == "200" ] || die "notflix: could not connect to 1337x.to."
+  result=$(curl -s -o /dev/null -w "%{http_code}" $baseurl)
+  failed=false
+  [ "$result" == "200" ] || failed=true
+  [ "$failed" = false ] || baseurl="https://1337x.gd/" 
+  [ "$failed" = false ] || result=$(curl -s -o /dev/null -w "%{http_code}" $baseurl)
+  [ "$result" == "200" ] || die "notflix: could not connect to 1337x."
 }
 
 checkDependencies
@@ -106,15 +111,15 @@ LINE=$(paste -d\   $cachedir/size.bw $cachedir/seedleech.bw $cachedir/titles.bw 
   cut -d\- -f1 |
   awk '{$1=$1; print}')
 
-[ -z "$LINE" ] && exit 0
+[ -z "$LINE" ] && exit 0 # silently exit if user didn't select anything
 url=$(head -n $LINE $cachedir/links.bw | tail -n +$LINE)
 fullURL="${baseurl}${url}/"
 
-# Requesting page for magnet link
+# grab magnet link from local html
 curl -s $fullURL > $cachedir/tmp.html
 magnet=$(grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" $cachedir/tmp.html | head -n 1)
 
-notify "notflix: launching webtorrent."
+echo "notflix: launching webtorrent."
 cleanup # cleanup before launching webtorrent
 webtorrent "$magnet" --$player --not-on-top --playlist
 
